version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
    ports:
     - 8081:8080
    volumes:
     - /var/run/docker.socket:/var/run/docker.socket
     - ./init.groovy.d:/usr/share/jenkins/ref/init.groovy.d


