version: "3.3"
services:
    master:
        hostname: master
        image: bfblog/spark:3.0.0
        command: ./sbin/start-master.sh
        environment: 
          - SPARK_NO_DAEMONIZE=1
        ports: 
          - 8080:8080
        networks: 
          - backend
        volumes: 
          - spark_data:/spark_data
    worker:
        image: bfblog/spark:3.0.0
        command: ./sbin/start-slave.sh spark://master:7077  --cores 2 --memory 2g
        depends_on: ["master"]
        environment: 
          - SPARK_NO_DAEMONIZE=1
        networks: 
          - backend
        volumes: 
          - spark_data:/spark_data
    ftp:
        image: stilliard/pure-ftpd
        environment: 
          - PUBLICHOST="localhost"
          - FTP_USER_NAME=spark
          - FTP_USER_PASS=1234 
          - FTP_USER_HOME=/spark_data
        ports:
          - "21:21"
          - "30000-30009:30000-30009"
        volumes: 
          - spark_data:/spark_data
volumes:
    spark_data:
networks: 
    backend: